import { useState } from 'react';

export const enterpriseGridData = () => {
    const [rowData, setRowData] = useState([
        {
            'Project Name': 'Project 1',
            State: 'Indianapolis',
            Country: 'United States',
            Started: new Date('2023-10-22'),
            Architect: 'Person A',
            Status: 'Open for Bids',
        },
        {
            'Project Name': 'Project 2',
            State: 'Andhra Pradesh',
            Country: 'India',
            Started: new Date('2023-10-22'),
            Architect: 'Person B',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 3',
            State: 'Eastern Cape',
            Country: 'South Africa',
            Started: new Date('2023-10-22'),
            Architect: 'Person C',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 4',
            State: 'Cusco',
            Country: 'Peru',
            Started: new Date('2022-10-22'),
            Architect: 'Person D',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 5',
            State: 'Bali',
            Country: 'Indonesia',
            Started: new Date('2023-10-22'),
            Architect: 'Person E',
            Status: 'Open for Bids',
        },
        {
            'Project Name': 'Project 6',
            State: 'Queensland',
            Country: 'Australia',
            Started: new Date('2023-11-15'),
            Architect: 'Person F',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 7',
            State: 'Bavaria',
            Country: 'Germany',
            Started: new Date('2022-09-10'),
            Architect: 'Person G',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 8',
            State: 'British Columbia',
            Country: 'Canada',
            Started: new Date('2023-05-30'),
            Architect: 'Person H',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 9',
            State: 'Rio de Janeiro',
            Country: 'Brazil',
            Started: new Date('2023-07-12'),
            Architect: 'Person I',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 10',
            State: 'Lombardy',
            Country: 'Italy',
            Started: new Date('2021-08-22'),
            Architect: 'Person J',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 11',
            State: 'Hokkaido',
            Country: 'Japan',
            Started: new Date('2023-12-05'),
            Architect: 'Person K',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 12',
            State: 'Western Cape',
            Country: 'South Africa',
            Started: new Date('2022-06-18'),
            Architect: 'Person L',
            Status: 'Open for Bids',
        },
        {
            'Project Name': 'Project 13',
            State: 'Île-de-France',
            Country: 'France',
            Started: new Date('2023-03-25'),
            Architect: 'Person M',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 14',
            State: 'Maharashtra',
            Country: 'India',
            Started: new Date('2022-04-17'),
            Architect: 'Person N',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 15',
            State: 'New South Wales',
            Country: 'Australia',
            Started: new Date('2023-02-14'),
            Architect: 'Person O',
            Status: 'Active',
        },
    ]);

    return { rowData, setRowData };
};
