import { useState } from 'react';

export const enterpriseGridData = () => {
    const [rowData, setRowData] = useState([
        {
            'Project Name': 'Project 1',
            State: 'Indianapolis',
            Country: 'United States',
            Started: '10/22/2023',
            Architect: 'Person A',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 2',
            State: 'Andhra Pradesh',
            Country: 'India',
            Started: '10/22/2023',
            Architect: 'Person B',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 3',
            State: 'Eastern Cape',
            Country: 'South Africa',
            Started: '10/22/2023',
            Architect: 'Person C',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 4',
            State: 'Cusco',
            Country: 'Peru',
            Started: '10/22/2022',
            Architect: 'Person D',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 5',
            State: 'Bali',
            Country: 'Indonesia',
            Started: '10/22/2023',
            Architect: 'Person E',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 6',
            State: 'Queensland',
            Country: 'Australia',
            Started: '11/15/2023',
            Architect: 'Person F',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 7',
            State: 'Bavaria',
            Country: 'Germany',
            Started: '09/10/2022',
            Architect: 'Person G',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 8',
            State: 'British Columbia',
            Country: 'Canada',
            Started: '05/30/2023',
            Architect: 'Person H',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 9',
            State: 'Rio de Janeiro',
            Country: 'Brazil',
            Started: '07/12/2023',
            Architect: 'Person I',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 10',
            State: 'Lombardy',
            Country: 'Italy',
            Started: '08/22/2021',
            Architect: 'Person J',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 11',
            State: 'Hokkaido',
            Country: 'Japan',
            Started: '12/05/2023',
            Architect: 'Person K',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 12',
            State: 'Western Cape',
            Country: 'South Africa',
            Started: '06/18/2022',
            Architect: 'Person L',
            Status: 'Active',
        },
        {
            'Project Name': 'Project 13',
            State: 'Île-de-France',
            Country: 'France',
            Started: '03/25/2023',
            Architect: 'Person M',
            Status: 'Complete',
        },
        {
            'Project Name': 'Project 14',
            State: 'Maharashtra',
            Country: 'India',
            Started: '04/17/2022',
            Architect: 'Person N',
            Status: 'Inactive',
        },
        {
            'Project Name': 'Project 15',
            State: 'New South Wales',
            Country: 'Australia',
            Started: '02/14/2023',
            Architect: 'Person O',
            Status: 'Active',
        },
    ]);

    return { rowData, setRowData };
};
